### ISSUE TITLE
Add Allison Parrish brilliant materials

### ISSUE THREAD

**Issue by villares** [xxyxyz/flat-examples#1]
Can I add these to the external resources?

Jupyter notebooks from the [Material of Language](https://mol.decontextualize.com/) course by Allison Parrish:
- [Asemic writing with Flat](https://github.com/aparrish/material-of-language/blob/master/flat-asemic-writing.ipynb)
- [Interactive art with ipywidgets and Flat](https://github.com/aparrish/material-of-language/blob/master/interactive-widgets.ipynb)
- [Creating animations with Flat and ffmpeg](https://github.com/aparrish/material-of-language/blob/master/creating-animations.ipynb)
- [Bezmerizing demo notebook](https://github.com/aparrish/bezmerizing/blob/master/demo.ipynb)

**Comment by sukop** [comment]
Of course!

**Comment by villares** [comment]
Ugh, maybe I should wait before closing it, or I should let you close it. I'm not very good at this, sorry.

**Comment by sukop** [comment]
It's fine, you raised the issue yourself.
