### ISSUE TITLE
Should I see an overprint preview on PDF?

### ISSUE THREAD

**Issue by villares** [xxyxyz/flat-examples#3]
As I tried this example:
![image](https://user-images.githubusercontent.com/3694604/91868431-18bd8f80-ec4b-11ea-9324-9d47b15738a0.png)

My resulting PDF looks different (no blending):

![image](https://user-images.githubusercontent.com/3694604/91868641-5ae6d100-ec4b-11ea-8639-0b7fa1e5f4fd.png)

Is this a system dependent issue, perhaps? Thanks for the attention.

**Comment by sukop** [comment]
Yes, it depends on the viewer, most are not able to simulate the overprint.
