### ISSUE TITLE
Where can we put the "historical examples"?

### ISSUE THREAD

**Issue by villares** [xxyxyz/flat-examples#4]
Should they go along with the external resources or somewere else?

- [Making of: Flat API tree](https://xxyxyz.org/making-of-tree/)
- [Line Breaking](https://xxyxyz.org/line-breaking/)
- [Bridges](https://xxyxyz.org/bridges/)
- [Rendering Tutorial](https://xxyxyz.org/rendering-tutorial/)

I found those using Duck Duck Go, there may be more, I don't know.

**Comment by sukop** [comment]
No, not really, they are part of the "blog" and the article on line breaking is not specific to Flat. I'm still trying to decide whether to fix (and how) the old examples which are not working anymore so closing this in favour of https://github.com/xxyxyz/flat/issues/13.
